#! /bin/sh

name=kernel
version=0.0
revision=1
source_dir="kernel"
source_imagedeps="git meson ninja-build"
source_allow_network="yes"
hostdeps="gcc"
imagedeps="nasm"
deps="core-libs"

prepare() {
    ./get-deps
}

build() {
    cp -rpf "${source_dir}"/. ./

    make -j${parallelism} \
        CFLAGS="$KERNEL_CFLAGS -O2 -pipe" \
        CC=${OS_TRIPLET}-gcc \
        AR=${OS_TRIPLET}-ar
}

package() {
    make install PREFIX="${prefix}" DESTDIR="${dest_dir}"

    post_package_strip
}
